services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5432:5432
